#!/bin/sh

# Exit immediately if a pipeline, a list, or a compound command, exits with a non-zero status.
set -o errexit
# Treat unset variables and parameters other than the special parameters "@" and "*" as an error when performing parameter expansion.
set -o nounset

# The version of https://github.com/concrete5/incremental-filter-branch to be used
IFB_VERSION=1.0.2

# Store in SCRIPT_DIR the directory that contains this script
# Please remark that this won't work in case of symlinks/hardlinks
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# Store in WORK_DIR the directory that will contain the working repositories
WORK_DIR=${SCRIPT_DIR}/temp

# Store in IFB_PATH the path of the incremental-filter-branch directory
IFB_PATH=${SCRIPT_DIR}/incremental-filter-branch-${IFB_VERSION}

# Store in IFB_BIN the path of the incremental-filter-branch command
IFB_BIN=${IFB_PATH}/bin/incremental-git-filterbranch

# Let's check if we don't have the incremental-filter-branch command
if ! test -f "${IFB_BIN}"
then
	# The incremental-filter-branch command does not exist locally: let's download it

	# Store in IFB_URL the path of the archive to be downloaded
	IFB_URL=https://github.com/concrete5/incremental-filter-branch/archive/${IFB_VERSION}.tar.gz

	# Store in IFB_ARCHIVE the path where the downloaded archive will be saved
	IFB_ARCHIVE=${SCRIPT_DIR}/incremental-filter-branch-${IFB_VERSION}.tar.gz

	# Download the archive
	echo "Downloading incremental-filter-branch ${IFB_VERSION}"
	if command -v curl >/dev/null # Do we have the cURL command?
	then
		# Download the archive with curl
		curl --output "${IFB_ARCHIVE}" --silent --show-error --location --fail --retry 5 "${IFB_URL}"
	elif command -v wget >/dev/null # Do we have the wget command?
	then
		# Download the archive with wget
		wget --output-file="${IFB_ARCHIVE}" --no-verbose --tries=5 "${IFB_URL}"
	else
		echo 'No command available to download the remote file.' >&2
		exit 1
	fi

	echo "Extracting incremental-filter-branch ${IFB_VERSION}"
	# Extract (-x) the (-z) GZIP archive from the (-f) specified file to (-C) the specified directory
	if ! tar -x -z -f "${IFB_ARCHIVE}" -C "${SCRIPT_DIR}"
	then
		# tar failed: let's delete the downloaded archive and the extracted dir
		unlink "${IFB_ARCHIVE}"
		rm -rf "${IFB_PATH}"
		exit 1
	fi

	# Cleanup: delete the downloaded archive
	unlink "${IFB_ARCHIVE}"

	# Finally check if we have the actual command
	if ! test -f "${IFB_BIN}"
	then
		rm -rf "${IFB_PATH}"
		echo 'Unable to find the incremental-git-filterbranch command'
		exit 1
	fi
fi

# Perform the incremental filter-branch operation
"${IFB_BIN}" \
	--workdir "${WORK_DIR}" \
	--branch-whitelist 'develop master rx:release\/.*' \
	--tag-blacklist 'rx:5\..*' \
	--prune-branches --prune-tags \
	--tags-plan all --tags-max-history-lookup 10 \
	-- \
	git@github.com:concrete5/concrete5.git \
	'--prune-empty --subdirectory-filter concrete' \
	git@github.com:concrete5/concrete5-core.git
